env = QT_QPA_PLATFORM,wayland
env = QT_QPA_PLATFORMTHEME,qt6ct
env = XDG_SESSION_TYPE,wayland

exec-once = awww-daemon
exec-once = /etc/awww/awww_randomize.sh
#exec-once = quickshell -p /etc/greetd/QuickshellGreeter.qml > /tmp/quickshell-error.log 2>&1
exec-once = quickshell -p /etc/greetd/QuickshellGreeter.qml; hyprctl dispatch exit

decoration {
    blur {
        enabled = true
        size = 8
        passes = 5

        vibrancy = 0.1696
	    #new_optimizations = true        
	    #ignore_opacity = false
    	#xray = false
	    popups = true
	    popups_ignorealpha = 0.1
    }
}

device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    disable_hyprland_guiutils_check = true
}

layerrule = blur on, match:namespace quickshell
layerrule = blur_popups on, match:namespace quickshell
layerrule = ignore_alpha 0.1, match:namespace quickshell

