general {
    lock_cmd = pidof hyprlock || hyprlock  # Optional: if you use hyprlock for screen locking
    after_sleep_cmd = hyprctl dispatch dpms on  # Ensures monitors turn back on after resume/suspend
}

listener {
    timeout = 300  # 5 minute (300 in seconds)
    on-timeout = hyprctl dispatch dpms off  # Turn off all monitors
    on-resume = hyprctl dispatch dpms on    # Turn monitors back on when you move mouse/type
}

#listener {
#    timeout = 1800 # 30 minutes
#    on-timeout = systemctl suspend
#}
