general {
    lock_cmd = ~/.config/quickshell/lock.sh
    before_sleep_cmd = loginctl lock-session && sleep 2
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && date +%s > /var/tmp/qs-wake
}

# Lock Screen
listener {
    timeout = 150  # 2.5 minute (150 in seconds)
    on-timeout = loginctl lock-session
}

# Sleep
listener {
    timeout = 3600 # 1 hour
    on-timeout = systemctl suspend
}
