-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
    general = {
        lock_cmd = "pidof hyprlock || hyprlock",
        -- Optional: if you use hyprlock for screen locking
        after_sleep_cmd = "hyprctl dispatch dpms on",
        -- Ensures monitors turn back on after resume/suspend
    },
})

hl.config({
    listener = {
        timeout = 300,
        -- 5 minute (300 in seconds)
        on-timeout = "hyprctl dispatch dpms off",
        -- Turn off all monitors
        on-resume = "hyprctl dispatch dpms on",
        -- Turn monitors back on when you move mouse/type
    },
})

-- NOTE: Section 'listener' may be a plugin or custom section; verify the output
--listener {
--    timeout = 1800 # 30 minutes
--    on-timeout = systemctl suspend
--}
