general {
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' # Ensures monitors turn back on after resume/suspend
}

listener {
    timeout = 300  # 5 minute (300 in seconds)
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })' # Turn off all monitors
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' # Turn monitors back on when you move mouse/type
}

listener {
    timeout = 1800                                # 30min
    on-timeout = systemctl suspend                # suspend pc
}
