general {
    lock_cmd = ~/.config/quickshell/lock/lock.sh
    before_sleep_cmd = loginctl lock-session && sleep 2
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && date +%s > /var/tmp/qs-wake
}

listener {
    timeout = 15  # 2.5 minute (150 in seconds)
    on-timeout = loginctl lock-session
}

listener {
    timeout = 30  # 5 minute (300 in seconds)
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })' # Turn off all monitors
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' # Turn monitors back on when you move mouse/type
}

listener {
    timeout = 3600                                # 1 hour
    on-timeout = systemctl suspend                # suspend pc
} 
