hl.on("hyprland.start", function()
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("quickshell")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("kitty --class kitty-autostart")
    hl.exec_cmd("/etc/awww/awww_randomize.sh /usr/share/backgrounds/anime")
    hl.exec_cmd("systemctl --user start sunshine")
    hl.exec_cmd("~/.config/hypr/scripts/autoconnect-last-headset.sh")
end)
